#! /usr/bin/env bash

_buildPullRequestPayload() {
  local id=${1};
  local repository=${2};
  local title=${3};

cat <<EOF
{
  "id": ${id},
  "url": "https://api.github.com/repos/${repository}/pulls/${id}",
  "html_url": "https://github.com/${repository}/pull/${id}",
  "diff_url": "https://github.com/${repository}/pull/${id}.diff",
  "patch_url": "https://github.com/${repository}/pull/${id}.patch",
  "issue_url": "https://api.github.com/repos/${repository}/issues/${id}",
  "commits_url": "https://api.github.com/repos/${repository}/pulls/${id}/commits",
  "review_comments_url": "https://api.github.com/repos/${repository}/pulls/${id}/comments",
  "review_comment_url": "https://api.github.com/repos/${repository}/pulls/comments{/number}",
  "comments_url": "https://api.github.com/repos/${repository}/issues/${id}/comments",
  "statuses_url": "https://api.github.com/repos/${repository}/statuses/6dcb09b5b57875f334f61aebed695e2e4193db5e",
  "number": ${id},
  "state": "open",
  "title": "${title}",
  "body": "Please pull these awesome changes",
  "assignee": {
    "login": "octocat",
    "id": 1,
    "avatar_url": "https://github.com/images/error/octocat_happy.gif",
    "gravatar_id": "",
    "url": "https://api.github.com/users/octocat",
    "html_url": "https://github.com/octocat",
    "followers_url": "https://api.github.com/users/octocat/followers",
    "following_url": "https://api.github.com/users/octocat/following{/other_user}",
    "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
    "organizations_url": "https://api.github.com/users/octocat/orgs",
    "repos_url": "https://api.github.com/users/octocat/repos",
    "events_url": "https://api.github.com/users/octocat/events{/privacy}",
    "received_events_url": "https://api.github.com/users/octocat/received_events",
    "type": "User",
    "site_admin": false
  }
EOF
}

_buildNotFoundPayload() {
cat <<EOF
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/pulls/#get-a-single-pull-request"
}
EOF
}

_token=$(echo ${*} | sed -E "s/-H[ ]+[\"']Authorization:[ ]*token[ ]+(.*)['\"].*/\1/");
_pullRequestNumber=$(echo ${*} | sed -E "s#.*/pulls/([0-9]+)#\1#");
_repository=$(echo ${*} | sed -E "s#.*/repos/(.*)/pulls/.*#\1#");
_response="";

if [ ${_pullRequestNumber} -eq 42 ]; then
  _response=$(_buildPullRequestPayload 42 "${_repository}" "Description of an issue");
elif [ ${_pullRequestNumber} -eq 1337 ]; then
  _response=$(_buildPullRequestPayload 1337 "${_repository}" "Another issue solved");
else
  _response=$(_buildNotFoundPayload);
fi

echo "${_response}";
